### ISSUE TITLE
Lavaplayer Version: 2.1.2YouTube Source Version: youtube:v2:1.3.0 IP rotation set up

### ISSUE THREAD

**Issue by lMolMol** [lavalink-devs/lavaplayer#137]
I am trying to set up IP rotation for YoutubeAudioSourceManager but I'm encountering an issue where I cannot import AbstractRoutePlanner or any classes from the extensions folder.

Dependencies in build.gradle:
dependencies {
    implementation 'dev.arbjerg:lavaplayer:2.1.2'
    implementation 'com.github.walkyst:lavaplayer-youtube-v2:1.3.0'
    implementation("net.dv8tion:JDA:5.0.0-beta.24")

    implementation("ch.qos.logback:logback-classic:1.5.6")

}

repositories {
    mavenCentral()
    maven {
        url 'https://m2.dv8tion.net/releases'
    }
    maven {
        url 'https://jitpack.io'
    }
    maven { url = "https://maven.lavalink.dev/releases" }
}

**Comment by devoxin** [comment]
`com.github.walkyst:lavaplayer-youtube-v2:1.3.0`
what is this...

**Comment by lMolMol** [comment]
> `com.github.walkyst:lavaplayer-youtube-v2:1.3.0` what is this...

aorr i made a mistake when copying the dependencies
it should be :
    implementation("dev.lavalink.youtube:v2:1.3.0") "it is the new youtube sorce 
    
 BTW 
 when i use 
     implementation 'com.github.devoxin:lavaplayer:1.9.1'
I can import AbstractRoutePlanner whithout any isseus

**Comment by devoxin** [comment]
With `dev.arbjerg.lavaplayer` you might need to import the `lavaplayer-ext-youtube-rotator` module.
https://maven.lavalink.dev/#/releases/dev/arbjerg/lavaplayer-ext-youtube-rotator

**Comment by lMolMol** [comment]
> With `dev.arbjerg.lavaplayer` you might need to import the `lavaplayer-ext-youtube-rotator` module separately. https://maven.lavalink.dev/#/releases/dev/arbjerg/lavaplayer-ext-youtube-rotator

fixed the issue Thanks!
