### ISSUE TITLE
Youtube outdated player

### ISSUE THREAD

**Issue by awesomekosm** [lavalink-devs/lavaplayer#139]
Trying to play anything on youtube and the result is out of date youtube player. This is on the latest version of lavaplayer has has been a problem for sometime.

<img width="966" alt="Screenshot 2024-06-22 at 1 37 07 AM" src="https://github.com/lavalink-devs/lavaplayer/assets/5395732/4665058f-8bae-409b-a5ff-49c6391843d0">

**Comment by Nansess** [comment]
https://github.com/lavalink-devs/youtube-source
