### ISSUE TITLE
Could not resolve on Gradle

### ISSUE THREAD

**Issue by DarkPizza** [lavalink-devs/lavaplayer#140]
Errors:

> MusicBot:main: Could not resolve dev.arbjerg:lavaplayer:2.2.0.
> Required by:
>     project :
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

> Task :prepareKotlinBuildScriptModel UP-TO-DATE
> Could not resolve: dev.arbjerg:lavaplayer:2.2.0
> Could not resolve: dev.arbjerg:lavaplayer:2.2.0
> 
> BUILD SUCCESSFUL in 388ms

My build.gradle is:
```
repositories {
    mavenCentral()
    maven { url "https://jitpack.io" } // For com.github.walkyst.JAADec-fork:jaadec-ext-aac & ibxm-fork:com.github.walkyst:ibxm-fork
}

dependencies {
    runtimeOnly 'dev.arbjerg:lavaplayer:2.2.0'
}
```
I tried to do it using Gradle 7.2 or 8.2 and Java 11 or 17 and was still unsuccessful.

What's wrong here?

**Comment by devoxin** [comment]
We do not use Jitpack for builds. We have our own Maven repository at https://maven.lavalink.dev

**Comment by devoxin** [comment]
Apparently `mavenCentral` is what the README suggests using. Not sure why it can't resolve an artifact from there, so I would recommend using https://maven.lavalink.dev/#/releases/dev/arbjerg/lavaplayer for grabbing artifacts instead.

If you head over to https://maven.lavalink.dev/#/ there's an example Gradle config on the right side of the page. You will need the `releases` repository
