### ISSUE TITLE
Playing YouTube Videos is not possible

### ISSUE THREAD

**Issue by Veqtive** [lavalink-devs/lavaplayer#145]
Console Log: 
> 19:26:39.996 [lava-daemon-pool-info-loader-2-thread-1] [WARN ] c.s.d.l.s.y.YoutubeAccessTokenTracker - YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
> 19:26:40.359 [lava-daemon-pool-info-loader-2-thread-1] [ERROR] c.s.d.l.s.y.YoutubeSignatureCipherManager - Problematic YouTube player script /s/player/1f8742dc/player_ias.vflset/de_DE/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\\\<user>\AppData\Local\Temp\lavaplayer-yt-player-script10527423578895379168.js

Using lavaplayer Version 2.2.1 with Maven and JavaSE-21 (jre)
```
 <dependency>
	<groupId>dev.arbjerg</groupId>
	<artifactId>lavaplayer</artifactId>
	<version>2.2.1</version>
</dependency>
```

I tried to implement a music bot functionality to my discord bot following [this YouTube Tutorial](https://www.youtube.com/watch?v=fr2xKaA8kq4). 
_Also checked the contents of this video with the [Usage from the readme](https://github.com/lavalink-devs/lavaplayer?tab=readme-ov-file#usage) and it looked all right to me, even though this tutorial used the original javaplayer repo by sedmelluq_

I can't imagine that the missing YouTube Auth Token is the reason for this error as this is just a warning and I tried to play non age restricted videos.
Other sources like twitch or http URLs work just fine so I rather don't think that this is due to my implementation.

**Comment by topi314** [comment]
The original YouTube source has been deprecated in https://github.com/lavalink-devs/lavaplayer/releases/tag/2.1.2

Please use the new source instead https://github.com/lavalink-devs/youtube-source/
