### ISSUE TITLE
Problematic Youtube player script (no n function match) in JMusicBot

### ISSUE THREAD

**Issue by pieterhouwen** [lavalink-devs/lavaplayer#147]
Hello,

If I am posting in the wrong place please let me know and close this issue.

I am running JMusicBot on my Discord server to play Youtube audio in voice chat. However when I try to play something the bot first does nothing until I skip to a random song in the playlist. 

When looking at the Github repo at: https://github.com/jagrosh/MusicBot I see in the Issues that they are using Lavaplayer for the playback so that's why I'm posting an issue here.

The error that I get when first adding a playlist to the queue is this:
```
[21:07:10] [ERROR] [SignatureCipherManager]: Problematic YouTube player script /s/player/1c78e434/player_ias.vflset/nl_NL/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script6983809891652923440.js
```

Please also see the script.
[lavaplayer-yt-player-script.txt](https://github.com/user-attachments/files/16591023/lavaplayer-yt-player-script.txt)

Again, if this is the wrong place to post this or if you need more details on my environment let me know, maybe this has to do with the implementation of the lavaplayer and not the lavaplayer itself.

Cheers!

**Comment by devoxin** [comment]
It appears that a fix has already been pushed for this in JMusicBot.

[Relevant PR #1655](https://github.com/jagrosh/MusicBot/pull/1655)

**Comment by pieterhouwen** [comment]
@devoxin Alright, thank you for your response. I will post the issues in the correct repo the next time :)
