### ISSUE TITLE
Failing To Build On Jitpack

### ISSUE THREAD

**Issue by 1A3Dev** [lavalink-devs/lavaplayer#59]
This repository is failing to build on [JitPack](https://jitpack.io/).

https://jitpack.io/com/github/lavalink-devs/lavaplayer/main-eb28477967-1/build.log

**Comment by topi314** [comment]
lavaplayer is published on maven central, no reason to use jitpack
https://central.sonatype.com/artifact/dev.arbjerg/lavaplayer

**Comment by 1A3Dev** [comment]
> lavaplayer is published on maven central, no reason to use jitpack https://central.sonatype.com/artifact/dev.arbjerg/lavaplayer

I've made a fork but I can't use it with maven easily due to jitpack not working.

**Comment by topi314** [comment]
this most likely has to do with jitpack using java 8 by default and lavaplayer requiring java 11

**Comment by topi314** [comment]
that being said, there should be no reason to use a fork in the first place, if something is broken simply pr a fix for it

**Comment by 1A3Dev** [comment]
> this most likely has to do with jitpack using java 8 by default and lavaplayer requiring java 11

Correct, making jitpack use java 11 seems to fix it.

> that being said, there should be no reason to use a fork in the first place, if something is broken simply pr a fix for it

It's not broken as per say, I just don't like the "Updating YouTube visitor id" logs.

**Comment by topi314** [comment]
> It's not broken as per say, I just don't like the "Updating YouTube visitor id" logs.

you can simply filter the logs out in either log4j or logback then
