### ISSUE TITLE
Lavaplayer fails to play Vimeo tracks due to empty "progressive" array, causing NPE

### ISSUE THREAD

**Issue by freyacodes** [lavalink-devs/lavaplayer#62]
Upon playing a Vimeo track, Lavaplayer downloads a track config from which it extracts `request.files.progressive[0].url`. However, on some tracks the `progressive` array is null, resulting in a NullPointerException. It appears that we need to add support for `hls` or `dash`.

![image](https://github.com/lavalink-devs/lavaplayer/assets/2582617/19bb83c8-44b8-4252-a1e0-b6a9db22461e)

Example url: https://vimeo.com/783006175

Track config url: https://player.vimeo.com/video/783006175/config?autopause=1&byline=0&collections=1&context=Vimeo%5CController%5CClipController.main&default_to_hd=1&h=250a7cefe0&outro=nothing&portrait=0&share=1&speed=1&title=0&watch_trailer=0&s=6ae0e5726574100d746264e851da4ccf6e8bd963_1704285204

Source: https://github.com/lavalink-devs/lavaplayer/blob/c363f956b67b3746f3d9a247c0289f2e726802e3/main/src/main/java/com/sedmelluq/discord/lavaplayer/source/vimeo/VimeoAudioTrack.java#L57-L67

**Comment by duncte123** [comment]
Looks like there are multiple CDNs as well, this is something to keep in mind when retrying to load the stream if one of them fails

**Comment by freyacodes** [comment]
Although I do not plan on any elaborate CDN fallback, I have been able to get HLS working. I will be submitting a PR later.
