### ISSUE TITLE
Something went wrong on playing

### ISSUE THREAD

**Issue by Fyphen1223** [lavalink-devs/lavaplayer#77]
I'm constantly getting this error message on LavaLink. How should I fix it?

```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track      
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.0.4.jar!/:na]
```

**Comment by topi314** [comment]
This is neither a lavalink bug tracker nor did you include any helpful information on what the issue is you are describing

**Comment by Fyphen1223** [comment]
Well, I think this is the error that described with some latest issues on lavalink, I was using Lavaplayer of 4.0.1, which is not good at handling yt, so, thankk you for your support anyway.
