### ISSUE TITLE
Add support for Discord authenticated media files

### ISSUE THREAD

**Issue by niridya** [lavalink-devs/lavaplayer#78]
Hello,

I think it can be useful to add support for medial links uploaded on Discord's CDN.

Since the new CDN authentication system, Lavaplayer returns an empty content (even when adding valid authentication parameters):
```js
{ loadType: 'empty', data: null }
```

Lavaplayer version: 2.1.1.

**Comment by topi314** [comment]
I assume you are using lavalink?
works no issue for me
