### ISSUE TITLE
 TrackException - This video is not available during duration of a visitor Id

### ISSUE THREAD

**Issue by kikkia** [lavalink-devs/lavaplayer#82]
Lavalink 4.0.4
Ipv6 /48 rotation

I have begun noticing issues with a node that experiences temporary spans where all tracks attempting to be played, sending the following track exception event: 
```
TrackException(message=This video is not available, severity=COMMON, cause=com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is not available)
```
Looking into my logs it seems correlated to the lifespan of a visitor ID. 

1. Everything working as intended
2. Visitor ID refresh
3. Track exceptions begin appearing
4. 10 minutes elapse
5. Visitor ID is refreshed
6. Working as intended until maybe 6-10 hours later this happens again. 

The frequency seems to slowly be increasing.

**Comment by devoxin** [comment]
Please try the new [youtube source](https://github.com/lavalink-devs/youtube-source).
If you continue to experience this issue, please create a new issue on that repository.
