### ISSUE TITLE
Fetching bug

### ISSUE THREAD

**Issue by SquareCodeFX** [lavalink-devs/lavaplayer#89]
Fetching new youtube video: Video returned by YouTube isn't what was requested

Ref: https://github.com/iv-org/invidious/issues/3822

**Comment by devoxin** [comment]
Fixed by #87, #88

**Comment by SquareCodeFX** [comment]
> Fixed by #87, #88

Well but not in master atm

**Comment by devoxin** [comment]
Hence why I haven't closed the issue. This issue will be closed when those PRs are merged but they are currently in testing phase (with what seems to be success thus far).

In the meantime, you can use the fixes by pulling in the snapshot jars from https://maven.lavalink.dev/#/snapshots.

**Comment by SquareCodeFX** [comment]
Cant resolve https://maven.lavalink.dev/#/snapshots

**Comment by devoxin** [comment]
To avoid spamming this issue, can you join [the Discord server](https://discord.gg/ZW4s47Ppw4) and tag me?

**Comment by SquareCodeFX** [comment]
Ah now i can
