### ISSUE TITLE
Lavaplayer completely stopped working without giving any errors

### ISSUE THREAD

**Issue by MrPotatoezzz** [lavalink-devs/lavaplayer#90]
Lavaplayer completely stopped playing music. I get no errors in console, so it's basically impossible to debug. Sorry that I can't provide more information, but it is all the information I have.

**Comment by devoxin** [comment]
Do you log track exception events?

**Comment by MrPotatoezzz** [comment]
Sorry. I thought I was using lavalink, but I'm using Lavaplayer. This is the maven dependency I use: ````
<dependency>
        <groupId>dev.arbjerg</groupId>
        <artifactId>lavaplayer</artifactId>
        <version>2.1.1</version>
      </dependency>
```` I do not log track events. Lavaplayer worked perfectly fine for the past few months. It only broke once when it needed to be updated, but it doesn't seem like there is a newer version available right now.

**Comment by devoxin** [comment]
> I do not log track events
You should. If there's an error, it'll tell you.

> Lavaplayer worked perfectly fine for the past few months. It only broke once when it needed to be updated
This doesn't matter. Lavaplayer's scraping nature means stuff will break with no notice.

> it doesn't seem like there is a newer version available right now
There is, it's on the `use-web-client` branch.

**Comment by JustRed23** [comment]
I am also experiencing some issues, I do not get a stacktrace, but the friendly exception does give me some info:
`Could not load track: Video returned by YouTube isn't what was requested`

**Comment by devoxin** [comment]
> I am also experiencing some issues, I do not get a stacktrace, but the friendly exception does give me some info: `Could not load track: Video returned by YouTube isn't what was requested`

#84, #89

**Comment by Korolz** [comment]
Unfortunately, I also encountered a similar problem with launching tracks from Youtube. Everything was working great, but a couple of weeks ago my bot would sometimes stop playing tracks, throwing a `FriendlyException`.
After the release of version 2.1.1, I immediately updated LavaPlayer and the problem went away for a while, but now it has returned again and for the second day any track from Youtube returns `FriendlyException` with the `COMMON` severity type.
I will be glad if you can find a solution to this problem or at least a workaround

**Comment by devoxin** [comment]
> Unfortunately, I also encountered a similar problem with launching tracks from Youtube. Everything was working great, but a couple of weeks ago my bot would sometimes stop playing tracks, throwing a `FriendlyException`. After the release of version 2.1.1, I immediately updated LavaPlayer and the problem went away for a while, but now it has returned again and for the second day any track from Youtube returns `FriendlyException` with the `COMMON` severity type. I will be glad if you can find a solution to this problem or at least a workaround

And those exceptions are usually accompanied with a message and possibly a stacktrace. What you have provided is everything but and basically impossible to diagnose any errors from as there are so many `COMMON` severity `FriendlyException`s.

If I had to guess, you're experiencing the same issue as everyone else in the thread.

#84 #89

**Comment by JamesEArnold** [comment]
For anyone else who was struggling to find the dependency that fixes this:

```
  <repository>
  	<id>arbjergDev-snapshots</id>
  	<name>Lavalink Repository</name>
  	<url>https://maven.lavalink.dev/snapshots</url>
  </repository>

<dependency>
  <groupId>dev.arbjerg</groupId>
  <artifactId>lavaplayer</artifactId>
  <version>0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT</version>
</dependency>

**Comment by DxsSucuk** [comment]
Any bump ups on the branch? Since its 4 commits behind with a few quality of life changes.

**Comment by topi314** [comment]
Use https://github.com/lavalink-devs/youtube-source/
